### ISSUE TITLE
add message that only CSV is accepted

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/DataBank#29]

**Comment by RyanHaniff** [comment]
- CSV and TSV accepted
- have a note on the webpage that it only accepts CSV and TSV
- If a file is drag and dropped and it's not CSV or TSV have a pop-up
- verify file superficially (file extension is .csv or .tsv) 
- Verify commas are properly formatted for CSV
- Verify tabs are properly formatted for TSV
