### ISSUE TITLE
Refactor Users

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/DataBank#36]
Right now, verified refers to whether the email is confirmed. This needs to change so that verified can refer to custom rules.

Things to Do:
- Replace `isVerified` with `confirmedAt`, where `null` or `undefined` means the user is not confirmed. This will require changing some things in the auth module. 
- Use `verifiedAt` to signify whether the user is verified (same thing, where null or undefined means the user is not verified). Base the verification method on the setup config. 
- Make sure email is unique and everything makes sense

**Comment by RyanHaniff** [comment]
![rn_image_picker_lib_temp_b3b01578-e309-42cf-82fd-023f9bb75323](https://github.com/DouglasNeuroInformatics/DataBank/assets/20189245/71c5e70b-0808-441b-b9bf-e119e3c09e17)

![rn_image_picker_lib_temp_e27af8a6-27fd-420a-ba2d-a630e2d42d08](https://github.com/DouglasNeuroInformatics/DataBank/assets/20189245/2a668dc2-eeb5-4e4f-b9e3-6697f5e2afe3)

**Comment by Flyinchicken** [comment]
users class has been refactored
