### ISSUE TITLE
Implement Verification

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/DataBank#37]
Implement an optional env variable`VERIFIED_EMAIL_REGEX` where they specify the regex for a email to be considered verified once it is confirmed. Once this is complete, adjust the verification logic in the `auth` accordingly.

**Comment by Flyinchicken** [comment]
The admin can set the verification method on the setup page when they first launch the app. It can be either manual verification, verification when users confirm their email, or verification by matching the user's email with a predefined regex set by the admin.
